import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'es' | 'zh' | 'ru'

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navbar
    'nav.managed': 'Managed AV',
    'nav.production': 'Production',
    'nav.equipment': 'Equipment',
    'nav.industries': 'Industries',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.quote': 'Start a Conversation',

    // Hero
    'hero.badge': 'Open Video Infrastructure Platform',
    'hero.title.1': 'The open platform for',
    'hero.title.2': 'video infrastructure',
    'hero.title.3': '— interoperable, managed, and built for organizations that',
    'hero.title.4': 'cannot afford to miss a moment',
    'hero.subtitle': 'THK integrates with Epiphan Pearl encoders, your existing LMS, and any cloud provider. No vendor lock-in. Remote-managed video infrastructure at $50–75/device/month — with an AI assistant available right now to answer questions.',
    'hero.cta.industries': 'Explore Industries',
    'hero.cta.services': 'See How It Works',
    'hero.cta.quote': 'Talk to Our AI Now',

    // Stats
    'stats.industries': 'Industries Served',
    'stats.uptime': 'Uptime SLA',
    'stats.monitoring': 'Cloud Monitoring',
    'stats.price': 'USD / Mo / Device',

    // How It Works
    'how.tag': 'How It Works',
    'how.title': 'Simple Setup, Reliable Recording',
    'how.subtitle': 'Our goal: make professional video infrastructure accessible to organizations of any size.',
    'how.step1.title': 'Setup',
    'how.step1.desc': 'We help you get Epiphan Pearl encoders configured and connected at your location.',
    'how.step2.title': 'Connect',
    'how.step2.desc': 'Plug in your HDMI sources (laptops, cameras, document cams) and connect to your network.',
    'how.step3.title': 'Monitor',
    'how.step3.desc': 'AI-powered monitoring watches your encoders and alerts us if anything needs attention.',
    'how.step4.title': 'Record',
    'how.step4.desc': 'Focus on your content. The system handles recording, streaming, and archiving.',

    // Managed Services
    'managed.tag': 'Managed AV',
    'managed.title': 'Video Infrastructure as a Service (VIaaS)',
    'managed.subtitle': 'Professional Epiphan encoders at your location, managed remotely.',
    'managed.viaas.title': 'VIaaS - Managed Encoder',
    'managed.viaas.desc': 'We help deploy a Pearl encoder at your location and manage it remotely. Recording, streaming, and monitoring included.',
    'managed.viaas.price': '$50-75 USD',
    'managed.viaas.unit': 'per device/month',
    'managed.lecture.title': 'Lecture Capture',
    'managed.lecture.desc': 'Automated lecture recording with calendar integration. Every class captured, every time.',
    'managed.lecture.price': '$75 USD',
    'managed.lecture.unit': 'per room/month',
    'managed.cloud.title': 'Cloud Management',
    'managed.cloud.desc': 'Epiphan Cloud integration for remote scheduling, monitoring, and firmware updates.',
    'managed.cloud.price': 'Included',
    'managed.cloud.unit': 'with VIaaS',

    // Event Production
    'event.tag': 'Event Production',
    'event.title': 'Professional Video Production',
    'event.subtitle': 'From livestreams to cinematic video, we bring your vision to life.',
    'event.livestream.title': 'Multi-Camera Livestreaming',
    'event.livestream.desc': 'Professional multi-camera switching and encoding for conferences, graduations, and events.',
    'event.livestream.price': 'From $5,000 MXN',
    'event.livestream.unit': 'per event',
    'event.video.title': '4K Video Production',
    'event.video.desc': 'Cinematic video production for commercials, documentaries, and promotional content.',
    'event.video.price': 'From $15,000 MXN',
    'event.video.unit': 'per project',
    'event.social.title': 'Social Media Streaming',
    'event.social.desc': 'Optimized streams for YouTube, Facebook, Instagram, and TikTok.',
    'event.social.price': 'From $3,000 MXN',
    'event.social.unit': 'per event',
    'event.rental.title': 'Equipment Rental',
    'event.rental.desc': 'Pearl encoders, PTZ cameras, and production gear for your team.',
    'event.rental.price': 'From $2,000 MXN',
    'event.rental.unit': 'per day',

    // Equipment
    'equipment.tag': 'Our Equipment',
    'equipment.title': 'Professional-Grade Hardware',
    'equipment.subtitle': 'We use Epiphan Pearl encoders trusted by organizations worldwide.',
    'equipment.nexus.name': 'Epiphan Pearl Nexus',
    'equipment.nexus.desc': '1RU rackmount encoder. 3 HD inputs, H.264/H.265, 1TB SSD, full REST API.',
    'equipment.nexus.badge': 'Rackmount - Fleet-Ready',
    'equipment.mini.name': 'Epiphan Pearl Mini',
    'equipment.mini.desc': 'Portable all-in-one live production system. Multi-source switching, recording, and streaming.',
    'equipment.mini.badge': 'Portable - Event-Ready',
    'equipment.camera.name': 'Epiphan EC20 PTZ Camera',
    'equipment.camera.desc': '4K60 PTZ camera with 20x optical zoom. NDI, SDI, HDMI, and USB output. Advanced AI tracking.',
    'equipment.camera.badge': 'Professional PTZ',
    'equipment.cloud.name': 'Epiphan Cloud',
    'equipment.cloud.desc': 'Cloud management platform. Remote scheduling, firmware updates, health monitoring.',
    'equipment.cloud.badge': '24/7 Cloud Control',
    'equipment.ai.name': 'THK AI Operations',
    'equipment.ai.desc': 'Our AI-powered monitoring agents. Automated quality checks and proactive alerts.',
    'equipment.ai.badge': 'Smart Automation',
    'equipment.ops.name': 'THK Operations Center',
    'equipment.ops.desc': 'Our Mexico City command center. Monitoring, support, and remote management.',
    'equipment.ops.badge': 'Operations HQ',

    // Verticals
    'verticals.tag': 'Industries We Serve',
    'verticals.title': 'Built for Organizations That Cannot Afford to Miss a Moment',
    'verticals.subtitle': 'We serve organizations that need reliable video but don\'t have the budget for a full-time AV team.',
    'verticals.universities': 'Universities',
    'verticals.universities.desc': 'Automated lecture capture and graduation streaming',
    'verticals.k12': 'K-12 Schools',
    'verticals.k12.desc': 'School events and parent broadcasts',
    'verticals.corporate': 'Corporate',
    'verticals.corporate.desc': 'Town halls, training, and product launches',
    'verticals.worship': 'Houses of Worship',
    'verticals.worship.desc': 'Weekly service streaming and community broadcasts',
    'verticals.legal': 'Legal / Courts',
    'verticals.legal.desc': 'Depositions, hearings, and secure recordings',
    'verticals.events': 'Events & Conferences',
    'verticals.events.desc': 'Multi-day conferences, galas, and trade shows',
    'verticals.healthcare': 'Healthcare',
    'verticals.healthcare.desc': 'Medical training, telemedicine, and procedures',
    'verticals.government': 'Government',
    'verticals.government.desc': 'Public meetings, council sessions, and archives',
    'verticals.broadcast': 'Broadcast',
    'verticals.broadcast.desc': 'Studio production and live programming',
    'verticals.nonprofit': 'Non-Profits',
    'verticals.nonprofit.desc': 'Donor events and awareness campaigns',

    // Why THK
    'why.tag': 'Why THK',
    'why.title': 'An Open Platform, Not a Closed System',
    'why.subtitle': 'THK connects to the tools you already use. Epiphan Cloud, your LMS, your cloud storage — without locking you in.',
    'why.cost.title': 'Fraction of the Cost',
    'why.cost.desc': '$50-75/month per device vs. $50,000/year for a full-time AV tech.',
    'why.trilingual.title': 'Trilingual Support',
    'why.trilingual.desc': 'English, Spanish, and Mandarin support for global organizations.',
    'why.uptime.title': 'Reliable Recording',
    'why.uptime.desc': 'AI-powered monitoring catches issues before they become problems.',
    'why.managed.title': 'Fully Managed',
    'why.managed.desc': 'We handle scheduling, firmware updates, and troubleshooting remotely.',
    'why.ai.title': 'AI-Powered Operations',
    'why.ai.desc': 'Our AI agents monitor quality, detect issues, and alert our team instantly.',
    'why.analytics.title': 'Analytics & Reports',
    'why.analytics.desc': 'Monthly reports on recording success rates, viewer engagement, and usage.',
    'why.open.title': 'Open Ecosystem',
    'why.open.desc': 'Works with Epiphan Cloud, Kaltura, Panopto, S3, and more. Bring your existing tools — we integrate, not replace.',

    // About
    'about.tag': 'About THK',
    'about.title': 'Built Different',
    'about.p1': 'THK Enterprises was founded by Timothy, an 11-year-old entrepreneur in Mexico City who saw a gap in the market: organizations need professional video infrastructure but can\'t afford full-time AV staff.',
    'about.p2': 'We leverage Epiphan\'s enterprise-grade Pearl encoders, cloud management, and our own AI monitoring to deliver broadcast-quality video at a fraction of the traditional cost.',
    'about.p3': 'Our AI assistant (powered by Claude) runs 24/7 — available right now to answer questions about integration, pricing, or fit. Organizations should be able to evaluate a platform at any hour, not just during business hours.',

    // Contact
    'contact.tag': 'Connect',
    'contact.title': 'Start a Conversation',
    'contact.subtitle': 'Our AI assistant is available right now. The form below goes to a real inbox — no auto-replies, no wait time promises.',
    'contact.info': 'Contact Information',
    'contact.info.desc': 'Based in Mexico City. We work with organizations across Latin America and North America.',
    'contact.location': 'Location',
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.availability': 'AI Assistant',
    'contact.availability.value': 'Available 24/7 — talk to it now',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone / WhatsApp',
    'contact.form.service': 'What do you need?',
    'contact.form.service.select': 'Select a service',
    'contact.form.service.viaas': 'VIaaS - Managed Encoder',
    'contact.form.service.lecture': 'Always-On Lecture Capture',
    'contact.form.service.livestream': 'Multi-Camera Livestreaming',
    'contact.form.service.video': '4K Video Production',
    'contact.form.message': 'Tell us about your needs',
    'contact.form.message.placeholder': 'How many rooms/locations? What are you recording?',
    'contact.form.submit': 'Send Message',
    'contact.form.disclaimer': 'No spam. No pressure. Your information stays private.',
    'contact.form.note': 'Prefer to type? Use the form. Prefer to talk now? The chat below is live.',

    // Footer
    'footer.rights': 'THK Enterprises. Mexico City. All rights reserved.',
    'footer.epiphan': 'Powered by Epiphan Video',

    // Chat
    'chat.placeholder': 'Ask about our video services...',
    'chat.powered': 'Powered by Claude AI',
    'chat.cta.label': 'Ask anything — live now',

    // Form states
    'contact.form.success': 'Message sent. We have it.',
    'contact.form.error': 'Something went wrong. Try the chat instead.',
    'contact.form.sending': 'Sending...',

    // Hero sub-label
    'hero.cta.chat.sub': 'No forms. Instant answers.',
  },

  es: {
    // Navbar
    'nav.managed': 'AV Administrado',
    'nav.production': 'Producción',
    'nav.equipment': 'Equipo',
    'nav.industries': 'Industrias',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.quote': 'Iniciar Conversación',

    // Hero
    'hero.badge': 'Plataforma Abierta de Infraestructura de Video',
    'hero.title.1': 'La plataforma abierta de',
    'hero.title.2': 'infraestructura de video',
    'hero.title.3': '— interoperable, administrada y diseñada para organizaciones que',
    'hero.title.4': 'no pueden perder un momento',
    'hero.subtitle': 'THK se integra con encoders Epiphan Pearl, tu LMS existente y cualquier proveedor de nube. Sin dependencia de proveedor. Infraestructura de video administrada remotamente a $50–75/dispositivo/mes — con un asistente de IA disponible ahora mismo para responder preguntas.',
    'hero.cta.industries': 'Ver Industrias',
    'hero.cta.services': 'Ver Cómo Funciona',
    'hero.cta.quote': 'Hablar con Nuestra IA',

    // Stats
    'stats.industries': 'Industrias Atendidas',
    'stats.uptime': 'SLA de Disponibilidad',
    'stats.monitoring': 'Monitoreo en la Nube',
    'stats.price': 'USD / Mes / Equipo',

    // How It Works
    'how.tag': 'Cómo Funciona',
    'how.title': 'Configuración Simple, Grabación Confiable',
    'how.subtitle': 'Nuestra meta: hacer la infraestructura de video profesional accesible para organizaciones de cualquier tamaño.',
    'how.step1.title': 'Configurar',
    'how.step1.desc': 'Te ayudamos a configurar y conectar los encoders Epiphan Pearl en tu ubicación.',
    'how.step2.title': 'Conectar',
    'how.step2.desc': 'Conecta tus fuentes HDMI (laptops, cámaras, documentos) y conéctalas a tu red.',
    'how.step3.title': 'Monitorear',
    'how.step3.desc': 'El monitoreo con IA vigila tus encoders y nos alerta si algo necesita atención.',
    'how.step4.title': 'Grabar',
    'how.step4.desc': 'Enfócate en tu contenido. El sistema maneja la grabación, streaming y archivo.',

    // Managed Services
    'managed.tag': 'AV Administrado',
    'managed.title': 'Infraestructura de Video como Servicio (VIaaS)',
    'managed.subtitle': 'Encoders Epiphan profesionales en tu ubicación, administrados remotamente.',
    'managed.viaas.title': 'VIaaS - Encoder Administrado',
    'managed.viaas.desc': 'Te ayudamos a instalar un encoder Pearl en tu ubicación y lo administramos remotamente. Grabación, streaming y monitoreo incluidos.',
    'managed.viaas.price': '$50-75 USD',
    'managed.viaas.unit': 'por equipo/mes',
    'managed.lecture.title': 'Captura de Clases',
    'managed.lecture.desc': 'Grabación automática de clases con integración de calendario. Cada clase capturada, siempre.',
    'managed.lecture.price': '$75 USD',
    'managed.lecture.unit': 'por sala/mes',
    'managed.cloud.title': 'Gestión en la Nube',
    'managed.cloud.desc': 'Integración con Epiphan Cloud para programación remota, monitoreo y actualizaciones.',
    'managed.cloud.price': 'Incluido',
    'managed.cloud.unit': 'con VIaaS',

    // Event Production
    'event.tag': 'Producción de Eventos',
    'event.title': 'Producción de Video Profesional',
    'event.subtitle': 'Desde livestreams hasta video cinematográfico, damos vida a tu visión.',
    'event.livestream.title': 'Livestreaming Multi-Cámara',
    'event.livestream.desc': 'Switching y encoding profesional multi-cámara para conferencias, graduaciones y eventos.',
    'event.livestream.price': 'Desde $5,000 MXN',
    'event.livestream.unit': 'por evento',
    'event.video.title': 'Producción de Video 4K',
    'event.video.desc': 'Producción de video cinematográfico para comerciales, documentales y contenido promocional.',
    'event.video.price': 'Desde $15,000 MXN',
    'event.video.unit': 'por proyecto',
    'event.social.title': 'Streaming para Redes',
    'event.social.desc': 'Streams optimizados para YouTube, Facebook, Instagram y TikTok.',
    'event.social.price': 'Desde $3,000 MXN',
    'event.social.unit': 'por evento',
    'event.rental.title': 'Renta de Equipo',
    'event.rental.desc': 'Encoders Pearl, cámaras PTZ y equipo de producción para tu equipo.',
    'event.rental.price': 'Desde $2,000 MXN',
    'event.rental.unit': 'por día',

    // Equipment
    'equipment.tag': 'Nuestro Equipo',
    'equipment.title': 'Hardware de Grado Profesional',
    'equipment.subtitle': 'Usamos encoders Epiphan Pearl confiados por organizaciones en todo el mundo.',
    'equipment.nexus.name': 'Epiphan Pearl Nexus',
    'equipment.nexus.desc': 'Encoder rackmount 1RU. 3 entradas HD, H.264/H.265, 1TB SSD, API REST completa.',
    'equipment.nexus.badge': 'Rackmount - Listo para Flota',
    'equipment.mini.name': 'Epiphan Pearl Mini',
    'equipment.mini.desc': 'Sistema portátil de producción en vivo todo-en-uno. Switching multi-fuente, grabación y streaming.',
    'equipment.mini.badge': 'Portátil - Listo para Eventos',
    'equipment.camera.name': 'Epiphan EC20 PTZ Camera',
    'equipment.camera.desc': 'Cámara PTZ 4K60 con zoom óptico 20x. Salida NDI, SDI, HDMI y USB. Tracking con IA.',
    'equipment.camera.badge': 'PTZ Profesional',
    'equipment.cloud.name': 'Epiphan Cloud',
    'equipment.cloud.desc': 'Plataforma de gestión en la nube. Programación remota, actualizaciones, monitoreo de salud.',
    'equipment.cloud.badge': 'Control 24/7 en la Nube',
    'equipment.ai.name': 'THK AI Operations',
    'equipment.ai.desc': 'Nuestros agentes de monitoreo con IA. Verificaciones de calidad automáticas y alertas proactivas.',
    'equipment.ai.badge': 'Automatización Inteligente',
    'equipment.ops.name': 'Centro de Operaciones THK',
    'equipment.ops.desc': 'Nuestro centro de comando en CDMX. Monitoreo, soporte y gestión remota.',
    'equipment.ops.badge': 'HQ de Operaciones',

    // Verticals
    'verticals.tag': 'Industrias que Atendemos',
    'verticals.title': 'Diseñado para Organizaciones que No Pueden Perder un Momento',
    'verticals.subtitle': 'Atendemos organizaciones que necesitan video confiable pero no tienen presupuesto para un técnico AV de tiempo completo.',
    'verticals.universities': 'Universidades',
    'verticals.universities.desc': 'Captura automática de clases y streaming de graduaciones',
    'verticals.k12': 'Escuelas K-12',
    'verticals.k12.desc': 'Eventos escolares y transmisiones para padres',
    'verticals.corporate': 'Corporativo',
    'verticals.corporate.desc': 'Town halls, capacitación y lanzamientos de productos',
    'verticals.worship': 'Iglesias',
    'verticals.worship.desc': 'Streaming de servicios semanales y transmisiones comunitarias',
    'verticals.legal': 'Legal / Juzgados',
    'verticals.legal.desc': 'Deposiciones, audiencias y grabaciones seguras',
    'verticals.events': 'Eventos y Conferencias',
    'verticals.events.desc': 'Conferencias de varios días, galas y ferias',
    'verticals.healthcare': 'Salud',
    'verticals.healthcare.desc': 'Capacitación médica, telemedicina y procedimientos',
    'verticals.government': 'Gobierno',
    'verticals.government.desc': 'Reuniones públicas, sesiones de consejo y archivos',
    'verticals.broadcast': 'Broadcast',
    'verticals.broadcast.desc': 'Producción de estudio y programación en vivo',
    'verticals.nonprofit': 'Sin Fines de Lucro',
    'verticals.nonprofit.desc': 'Eventos para donantes y campañas de concientización',

    // Why THK
    'why.tag': 'Por Qué THK',
    'why.title': 'Una Plataforma Abierta, No un Sistema Cerrado',
    'why.subtitle': 'THK se conecta a las herramientas que ya usas. Epiphan Cloud, tu LMS, tu almacenamiento en la nube — sin encerrarte con un proveedor.',
    'why.cost.title': 'Fracción del Costo',
    'why.cost.desc': '$50-75/mes por equipo vs. $50,000/año por un técnico AV de tiempo completo.',
    'why.trilingual.title': 'Soporte Trilingüe',
    'why.trilingual.desc': 'Soporte en inglés, español y mandarín para organizaciones globales.',
    'why.uptime.title': 'Grabación Confiable',
    'why.uptime.desc': 'Monitoreo con IA detecta problemas antes de que se conviertan en fallas.',
    'why.managed.title': 'Completamente Administrado',
    'why.managed.desc': 'Manejamos horarios, actualizaciones de firmware y solución de problemas remotamente.',
    'why.ai.title': 'Operaciones con IA',
    'why.ai.desc': 'Nuestros agentes de IA monitorean calidad, detectan problemas y alertan a nuestro equipo al instante.',
    'why.analytics.title': 'Analíticas y Reportes',
    'why.analytics.desc': 'Reportes mensuales de tasas de grabación exitosa, engagement de viewers y uso.',
    'why.open.title': 'Ecosistema Abierto',
    'why.open.desc': 'Funciona con Epiphan Cloud, Kaltura, Panopto, S3 y más. Trae tus herramientas existentes — integramos, no reemplazamos.',

    // About
    'about.tag': 'Sobre THK',
    'about.title': 'Construido Diferente',
    'about.p1': 'THK Enterprises fue fundada por Timothy, un emprendedor de 11 años en la Ciudad de México que vio una brecha en el mercado: las organizaciones necesitan infraestructura de video profesional pero no pueden pagar personal AV de tiempo completo.',
    'about.p2': 'Aprovechamos los encoders Pearl de grado empresarial de Epiphan, gestión en la nube y nuestro propio monitoreo con IA para entregar video de calidad de transmisión a una fracción del costo tradicional.',
    'about.p3': 'Nuestro asistente de IA (impulsado por Claude) funciona 24/7 — disponible ahora mismo para responder preguntas sobre integración, precios o compatibilidad. Las organizaciones deberían poder evaluar una plataforma a cualquier hora, no solo en horario de oficina.',

    // Contact
    'contact.tag': 'Conectar',
    'contact.title': 'Iniciar una Conversación',
    'contact.subtitle': 'Nuestro asistente de IA está disponible ahora mismo. El formulario de abajo va a una bandeja de entrada real — sin respuestas automáticas ni promesas de tiempo de espera.',
    'contact.info': 'Información de Contacto',
    'contact.info.desc': 'Con sede en Ciudad de México. Trabajamos con organizaciones en América Latina y América del Norte.',
    'contact.location': 'Ubicación',
    'contact.email': 'Correo',
    'contact.whatsapp': 'WhatsApp',
    'contact.availability': 'Asistente de IA',
    'contact.availability.value': 'Disponible 24/7 — habla ahora',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Correo',
    'contact.form.phone': 'Teléfono / WhatsApp',
    'contact.form.service': '¿Qué necesitas?',
    'contact.form.service.select': 'Selecciona un servicio',
    'contact.form.service.viaas': 'VIaaS - Encoder Administrado',
    'contact.form.service.lecture': 'Captura de Clases Siempre Activa',
    'contact.form.service.livestream': 'Livestreaming Multi-Cámara',
    'contact.form.service.video': 'Producción de Video 4K',
    'contact.form.message': 'Cuéntanos sobre tus necesidades',
    'contact.form.message.placeholder': '¿Cuántas salas/ubicaciones? ¿Qué estás grabando?',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.disclaimer': 'Sin spam. Sin presión. Tu información es privada.',
    'contact.form.note': '¿Prefieres escribir? Usa el formulario. ¿Prefieres hablar ahora? El chat abajo está en vivo.',

    // Footer
    'footer.rights': 'THK Enterprises. Ciudad de México. Todos los derechos reservados.',
    'footer.epiphan': 'Impulsado por Epiphan Video',

    // Chat
    'chat.placeholder': 'Pregunta sobre nuestros servicios de video...',
    'chat.powered': 'Impulsado por Claude AI',
    'chat.cta.label': 'Pregunta lo que quieras — en vivo ahora',

    // Form states
    'contact.form.success': 'Mensaje enviado. Lo tenemos.',
    'contact.form.error': 'Algo salió mal. Intenta con el chat.',
    'contact.form.sending': 'Enviando...',

    // Hero sub-label
    'hero.cta.chat.sub': 'Sin formularios. Respuestas instantáneas.',
  },

  zh: {
    // Navbar
    'nav.managed': '托管视听',
    'nav.production': '制作',
    'nav.equipment': '设备',
    'nav.industries': '行业',
    'nav.about': '关于',
    'nav.contact': '联系',
    'nav.quote': '开始对话',

    // Hero
    'hero.badge': '开放视频基础设施平台',
    'hero.title.1': '开放的',
    'hero.title.2': '视频基础设施',
    'hero.title.3': '平台 — 可互操作、全托管，专为不能错过任何时刻的',
    'hero.title.4': '机构而建',
    'hero.subtitle': 'THK 与 Epiphan Pearl 编码器、您现有的 LMS 和任何云服务商集成。无供应商锁定。远程管理的视频基础设施，每设备每月仅需 $50-75 美元 — AI 助手随时为您解答问题。',
    'hero.cta.industries': '浏览行业',
    'hero.cta.services': '了解运作方式',
    'hero.cta.quote': '与AI助手对话',

    // Stats
    'stats.industries': '服务行业',
    'stats.uptime': '运行时间 SLA',
    'stats.monitoring': '云端监控',
    'stats.price': '美元/月/设备',

    // How It Works
    'how.tag': '运作方式',
    'how.title': '简单部署，可靠录制',
    'how.subtitle': '我们的目标：让任何规模的机构都能使用专业视频基础设施。',
    'how.step1.title': '部署',
    'how.step1.desc': '我们帮助您在现场配置和连接 Epiphan Pearl 编码器。',
    'how.step2.title': '连接',
    'how.step2.desc': '连接您的 HDMI 信号源（笔记本电脑、摄像机、实物展台）并接入网络。',
    'how.step3.title': '监控',
    'how.step3.desc': 'AI 驱动的监控系统时刻关注您的编码器，有问题时立即提醒我们。',
    'how.step4.title': '录制',
    'how.step4.desc': '专注于您的内容。系统自动处理录制、直播和归档。',

    // Managed Services
    'managed.tag': '托管视听',
    'managed.title': '视频基础设施即服务 (VIaaS)',
    'managed.subtitle': '专业 Epiphan 编码器部署在您的现场，由我们远程管理。',
    'managed.viaas.title': 'VIaaS - 托管编码器',
    'managed.viaas.desc': '我们帮助在您的现场部署 Pearl 编码器并进行远程管理。包含录制、直播和监控。',
    'managed.viaas.price': '$50-75 美元',
    'managed.viaas.unit': '每设备/月',
    'managed.lecture.title': '课程录制',
    'managed.lecture.desc': '集成日历的自动课程录制。每堂课都能被捕获，永不遗漏。',
    'managed.lecture.price': '$75 美元',
    'managed.lecture.unit': '每教室/月',
    'managed.cloud.title': '云端管理',
    'managed.cloud.desc': 'Epiphan Cloud 集成，支持远程调度、监控和固件更新。',
    'managed.cloud.price': '包含',
    'managed.cloud.unit': '随 VIaaS 附赠',

    // Event Production
    'event.tag': '活动制作',
    'event.title': '专业视频制作',
    'event.subtitle': '从直播到电影级视频，我们将您的愿景变为现实。',
    'event.livestream.title': '多机位直播',
    'event.livestream.desc': '专业多机位切换和编码，适用于会议、毕业典礼和各类活动。',
    'event.livestream.price': '起步价 $5,000 墨西哥比索',
    'event.livestream.unit': '每场活动',
    'event.video.title': '4K 视频制作',
    'event.video.desc': '电影级视频制作，适用于广告、纪录片和宣传内容。',
    'event.video.price': '起步价 $15,000 墨西哥比索',
    'event.video.unit': '每个项目',
    'event.social.title': '社交媒体直播',
    'event.social.desc': '针对 YouTube、Facebook、Instagram 和 TikTok 优化的直播。',
    'event.social.price': '起步价 $3,000 墨西哥比索',
    'event.social.unit': '每场活动',
    'event.rental.title': '设备租赁',
    'event.rental.desc': 'Pearl 编码器、PTZ 摄像机和制作设备供您的团队使用。',
    'event.rental.price': '起步价 $2,000 墨西哥比索',
    'event.rental.unit': '每天',

    // Equipment
    'equipment.tag': '我们的设备',
    'equipment.title': '专业级硬件',
    'equipment.subtitle': '我们使用全球机构信赖的 Epiphan Pearl 编码器。',
    'equipment.nexus.name': 'Epiphan Pearl Nexus',
    'equipment.nexus.desc': '1U 机架式编码器。3路高清输入，H.264/H.265，1TB SSD，完整 REST API。',
    'equipment.nexus.badge': '机架式 - 可组建机群',
    'equipment.mini.name': 'Epiphan Pearl Mini',
    'equipment.mini.desc': '便携式一体化现场制作系统。多源切换、录制和直播。',
    'equipment.mini.badge': '便携式 - 活动就绪',
    'equipment.camera.name': 'Epiphan EC20 PTZ 摄像机',
    'equipment.camera.desc': '4K60 PTZ 摄像机，20倍光学变焦。NDI、SDI、HDMI 和 USB 输出。高级 AI 追踪。',
    'equipment.camera.badge': '专业 PTZ',
    'equipment.cloud.name': 'Epiphan Cloud',
    'equipment.cloud.desc': '云管理平台。远程调度、固件更新、健康监控。',
    'equipment.cloud.badge': '24/7 云端控制',
    'equipment.ai.name': 'THK AI 运维',
    'equipment.ai.desc': '我们的 AI 驱动监控代理。自动质量检查和主动预警。',
    'equipment.ai.badge': '智能自动化',
    'equipment.ops.name': 'THK 运营中心',
    'equipment.ops.desc': '我们在墨西哥城的指挥中心。监控、支持和远程管理。',
    'equipment.ops.badge': '运营总部',

    // Verticals
    'verticals.tag': '服务行业',
    'verticals.title': '为不能错过任何时刻的机构而建',
    'verticals.subtitle': '我们为需要可靠视频但无力聘请全职视听技术人员的机构提供服务。',
    'verticals.universities': '高等院校',
    'verticals.universities.desc': '自动课程录制和毕业典礼直播',
    'verticals.k12': 'K-12 学校',
    'verticals.k12.desc': '校园活动和家长直播',
    'verticals.corporate': '企业',
    'verticals.corporate.desc': '全体大会、培训和产品发布',
    'verticals.worship': '宗教场所',
    'verticals.worship.desc': '每周礼拜直播和社区广播',
    'verticals.legal': '法律/法院',
    'verticals.legal.desc': '证词录制、听证会和安全存档',
    'verticals.events': '活动与会议',
    'verticals.events.desc': '多日会议、晚宴和展览',
    'verticals.healthcare': '医疗',
    'verticals.healthcare.desc': '医学培训、远程医疗和手术录制',
    'verticals.government': '政府',
    'verticals.government.desc': '公开会议、议会会议和档案',
    'verticals.broadcast': '广播',
    'verticals.broadcast.desc': '演播室制作和现场节目',
    'verticals.nonprofit': '非营利组织',
    'verticals.nonprofit.desc': '捐赠者活动和公益宣传',

    // Why THK
    'why.tag': '为什么选择 THK',
    'why.title': '开放平台，而非封闭系统',
    'why.subtitle': 'THK 连接您已有的工具。Epiphan Cloud、您的 LMS、您的云存储 — 没有供应商锁定。',
    'why.cost.title': '低成本',
    'why.cost.desc': '每设备每月 $50-75 美元 vs. 全职视听技术人员每年 $50,000 美元。',
    'why.trilingual.title': '多语言支持',
    'why.trilingual.desc': '为全球机构提供英语、西班牙语和中文支持。',
    'why.uptime.title': '可靠录制',
    'why.uptime.desc': 'AI 驱动的监控在问题发生前就能发现它们。',
    'why.managed.title': '全面托管',
    'why.managed.desc': '我们远程处理日程安排、固件更新和故障排除。',
    'why.ai.title': 'AI 驱动运维',
    'why.ai.desc': '我们的 AI 代理实时监控质量、检测问题并即时通知团队。',
    'why.analytics.title': '分析与报告',
    'why.analytics.desc': '每月提供录制成功率、观众参与度和使用情况的报告。',
    'why.open.title': '开放生态',
    'why.open.desc': '兼容 Epiphan Cloud、Kaltura、Panopto、S3 等。带上您已有的工具 — 我们整合，而非替代。',

    // About
    'about.tag': '关于 THK',
    'about.title': '与众不同',
    'about.p1': 'THK Enterprises 由 Timothy 创立，他是一位来自墨西哥城的 11 岁创业者，他发现了市场空白：机构需要专业视频基础设施，却无法负担全职视听人员。',
    'about.p2': '我们利用 Epiphan 企业级 Pearl 编码器、云管理和自主研发的 AI 监控，以传统成本的零头提供广播级视频。',
    'about.p3': '我们的 AI 助手（由 Claude 驱动）全天候运行 — 随时可以回答有关集成、价格或适配性的问题。机构应该能在任何时间评估平台，而不仅仅是在工作时间。',

    // Contact
    'contact.tag': '联系我们',
    'contact.title': '开始对话',
    'contact.subtitle': '我们的 AI 助手现在就可以为您服务。下方的表单会发送到真实邮箱 — 没有自动回复，不承诺等待时间。',
    'contact.info': '联系方式',
    'contact.info.desc': '总部位于墨西哥城。我们为拉丁美洲和北美洲的机构提供服务。',
    'contact.location': '地址',
    'contact.email': '邮箱',
    'contact.whatsapp': 'WhatsApp',
    'contact.availability': 'AI 助手',
    'contact.availability.value': '24/7 全天候在线 — 立即对话',
    'contact.form.name': '姓名',
    'contact.form.email': '邮箱',
    'contact.form.phone': '电话 / WhatsApp',
    'contact.form.service': '您需要什么？',
    'contact.form.service.select': '选择一项服务',
    'contact.form.service.viaas': 'VIaaS - 托管编码器',
    'contact.form.service.lecture': '全天候课程录制',
    'contact.form.service.livestream': '多机位直播',
    'contact.form.service.video': '4K 视频制作',
    'contact.form.message': '请描述您的需求',
    'contact.form.message.placeholder': '多少个教室/场地？您需要录制什么？',
    'contact.form.submit': '发送消息',
    'contact.form.disclaimer': '无垃圾邮件。无压力。您的信息严格保密。',
    'contact.form.note': '喜欢文字？用表单。想立即交流？下方的聊天功能正在线上。',

    // Footer
    'footer.rights': 'THK Enterprises. 墨西哥城。保留所有权利。',
    'footer.epiphan': '由 Epiphan Video 提供支持',

    // Chat
    'chat.placeholder': '询问我们的视频服务...',
    'chat.powered': '由 Claude AI 驱动',
    'chat.cta.label': '随时提问 — 在线中',

    // Form states
    'contact.form.success': '消息已发送。我们已收到。',
    'contact.form.error': '出了点问题。请尝试使用聊天功能。',
    'contact.form.sending': '发送中...',

    // Hero sub-label
    'hero.cta.chat.sub': '无需填表。即时回复。',
  },

  ru: {
    // Navbar
    'nav.managed': 'Управление AV',
    'nav.production': 'Продакшн',
    'nav.equipment': 'Оборудование',
    'nav.industries': 'Отрасли',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.quote': 'Начать разговор',

    // Hero
    'hero.badge': 'Открытая платформа видеоинфраструктуры',
    'hero.title.1': 'Открытая платформа для',
    'hero.title.2': 'видеоинфраструктуры',
    'hero.title.3': '— совместимая, управляемая и созданная для организаций, которые',
    'hero.title.4': 'не могут упустить ни одного момента',
    'hero.subtitle': 'THK интегрируется с кодерами Epiphan Pearl, вашей LMS и любым облачным провайдером. Без привязки к поставщику. Удалённо управляемая видеоинфраструктура от $50–75/устройство/месяц — с AI-ассистентом, доступным прямо сейчас.',
    'hero.cta.industries': 'Обзор отраслей',
    'hero.cta.services': 'Как это работает',
    'hero.cta.quote': 'Поговорить с AI',

    // Stats
    'stats.industries': 'Обслуживаемые отрасли',
    'stats.uptime': 'SLA доступности',
    'stats.monitoring': 'Облачный мониторинг',
    'stats.price': 'USD / мес / устройство',

    // How It Works
    'how.tag': 'Как это работает',
    'how.title': 'Простая настройка, надёжная запись',
    'how.subtitle': 'Наша цель: сделать профессиональную видеоинфраструктуру доступной для организаций любого размера.',
    'how.step1.title': 'Настройка',
    'how.step1.desc': 'Мы помогаем настроить и подключить кодеры Epiphan Pearl на вашей площадке.',
    'how.step2.title': 'Подключение',
    'how.step2.desc': 'Подключите источники HDMI (ноутбуки, камеры, документ-камеры) к сети.',
    'how.step3.title': 'Мониторинг',
    'how.step3.desc': 'AI-мониторинг следит за кодерами и оповещает нас при любых проблемах.',
    'how.step4.title': 'Запись',
    'how.step4.desc': 'Сосредоточьтесь на контенте. Система сама записывает, транслирует и архивирует.',

    // Managed Services
    'managed.tag': 'Управление AV',
    'managed.title': 'Видеоинфраструктура как услуга (VIaaS)',
    'managed.subtitle': 'Профессиональные кодеры Epiphan на вашей площадке с удалённым управлением.',
    'managed.viaas.title': 'VIaaS - Управляемый кодер',
    'managed.viaas.desc': 'Мы разворачиваем кодер Pearl на вашей площадке и управляем им удалённо. Запись, трансляция и мониторинг включены.',
    'managed.viaas.price': '$50-75 USD',
    'managed.viaas.unit': 'за устройство/месяц',
    'managed.lecture.title': 'Запись лекций',
    'managed.lecture.desc': 'Автоматическая запись лекций с интеграцией календаря. Каждое занятие записано, каждый раз.',
    'managed.lecture.price': '$75 USD',
    'managed.lecture.unit': 'за аудиторию/месяц',
    'managed.cloud.title': 'Облачное управление',
    'managed.cloud.desc': 'Интеграция с Epiphan Cloud для удалённого планирования, мониторинга и обновления прошивки.',
    'managed.cloud.price': 'Включено',
    'managed.cloud.unit': 'с VIaaS',

    // Event Production
    'event.tag': 'Продакшн мероприятий',
    'event.title': 'Профессиональный видеопродакшн',
    'event.subtitle': 'От прямых трансляций до кинематографического видео — мы воплощаем ваше видение.',
    'event.livestream.title': 'Многокамерная трансляция',
    'event.livestream.desc': 'Профессиональное многокамерное переключение и кодирование для конференций, выпускных и мероприятий.',
    'event.livestream.price': 'От $5,000 MXN',
    'event.livestream.unit': 'за мероприятие',
    'event.video.title': '4K видеопродакшн',
    'event.video.desc': 'Кинематографическое видеопроизводство для рекламы, документальных фильмов и промоматериалов.',
    'event.video.price': 'От $15,000 MXN',
    'event.video.unit': 'за проект',
    'event.social.title': 'Стриминг в соцсети',
    'event.social.desc': 'Оптимизированные трансляции для YouTube, Facebook, Instagram и TikTok.',
    'event.social.price': 'От $3,000 MXN',
    'event.social.unit': 'за мероприятие',
    'event.rental.title': 'Аренда оборудования',
    'event.rental.desc': 'Кодеры Pearl, PTZ-камеры и продакшн-оборудование для вашей команды.',
    'event.rental.price': 'От $2,000 MXN',
    'event.rental.unit': 'за день',

    // Equipment
    'equipment.tag': 'Наше оборудование',
    'equipment.title': 'Оборудование профессионального класса',
    'equipment.subtitle': 'Мы используем кодеры Epiphan Pearl, которым доверяют организации по всему миру.',
    'equipment.nexus.name': 'Epiphan Pearl Nexus',
    'equipment.nexus.desc': '1U стоечный кодер. 3 HD-входа, H.264/H.265, 1TB SSD, полный REST API.',
    'equipment.nexus.badge': 'Стоечный - Для парка устройств',
    'equipment.mini.name': 'Epiphan Pearl Mini',
    'equipment.mini.desc': 'Портативная универсальная система прямого производства. Многоисточниковое переключение, запись и трансляция.',
    'equipment.mini.badge': 'Портативный - Для мероприятий',
    'equipment.camera.name': 'Epiphan EC20 PTZ камера',
    'equipment.camera.desc': '4K60 PTZ-камера с 20x оптическим зумом. Выходы NDI, SDI, HDMI и USB. AI-трекинг.',
    'equipment.camera.badge': 'Профессиональная PTZ',
    'equipment.cloud.name': 'Epiphan Cloud',
    'equipment.cloud.desc': 'Облачная платформа управления. Удалённое планирование, обновления прошивки, мониторинг состояния.',
    'equipment.cloud.badge': 'Облачный контроль 24/7',
    'equipment.ai.name': 'THK AI операции',
    'equipment.ai.desc': 'Наши AI-агенты мониторинга. Автоматические проверки качества и проактивные оповещения.',
    'equipment.ai.badge': 'Умная автоматизация',
    'equipment.ops.name': 'Операционный центр THK',
    'equipment.ops.desc': 'Наш командный центр в Мехико. Мониторинг, поддержка и удалённое управление.',
    'equipment.ops.badge': 'Штаб операций',

    // Verticals
    'verticals.tag': 'Обслуживаемые отрасли',
    'verticals.title': 'Создано для организаций, которые не могут упустить ни одного момента',
    'verticals.subtitle': 'Мы обслуживаем организации, которым нужно надёжное видео, но нет бюджета на штатного AV-специалиста.',
    'verticals.universities': 'Университеты',
    'verticals.universities.desc': 'Автоматическая запись лекций и трансляция выпускных',
    'verticals.k12': 'Школы K-12',
    'verticals.k12.desc': 'Школьные мероприятия и трансляции для родителей',
    'verticals.corporate': 'Корпоративный',
    'verticals.corporate.desc': 'Общие собрания, обучение и презентации продуктов',
    'verticals.worship': 'Религиозные учреждения',
    'verticals.worship.desc': 'Еженедельные трансляции служб и общественные трансляции',
    'verticals.legal': 'Юридический / Суды',
    'verticals.legal.desc': 'Показания, слушания и защищённые записи',
    'verticals.events': 'Мероприятия и конференции',
    'verticals.events.desc': 'Многодневные конференции, торжества и выставки',
    'verticals.healthcare': 'Здравоохранение',
    'verticals.healthcare.desc': 'Медицинское обучение, телемедицина и процедуры',
    'verticals.government': 'Государственный',
    'verticals.government.desc': 'Публичные заседания, советы и архивы',
    'verticals.broadcast': 'Вещание',
    'verticals.broadcast.desc': 'Студийное производство и прямой эфир',
    'verticals.nonprofit': 'Некоммерческие',
    'verticals.nonprofit.desc': 'Мероприятия для доноров и социальные кампании',

    // Why THK
    'why.tag': 'Почему THK',
    'why.title': 'Открытая платформа, а не закрытая система',
    'why.subtitle': 'THK подключается к инструментам, которые вы уже используете. Epiphan Cloud, ваша LMS, ваше облачное хранилище — без привязки к поставщику.',
    'why.cost.title': 'Низкая стоимость',
    'why.cost.desc': '$50-75/мес за устройство vs. $50,000/год за штатного AV-специалиста.',
    'why.trilingual.title': 'Мультиязычная поддержка',
    'why.trilingual.desc': 'Поддержка на английском, испанском и китайском для глобальных организаций.',
    'why.uptime.title': 'Надёжная запись',
    'why.uptime.desc': 'AI-мониторинг выявляет проблемы до того, как они станут критичными.',
    'why.managed.title': 'Полное управление',
    'why.managed.desc': 'Мы удалённо управляем расписанием, обновлениями прошивки и устранением неполадок.',
    'why.ai.title': 'AI-операции',
    'why.ai.desc': 'Наши AI-агенты мониторят качество, выявляют проблемы и мгновенно оповещают команду.',
    'why.analytics.title': 'Аналитика и отчёты',
    'why.analytics.desc': 'Ежемесячные отчёты по успешности записей, вовлечённости зрителей и использованию.',
    'why.open.title': 'Открытая экосистема',
    'why.open.desc': 'Работает с Epiphan Cloud, Kaltura, Panopto, S3 и другими. Используйте свои инструменты — мы интегрируем, а не заменяем.',

    // About
    'about.tag': 'О THK',
    'about.title': 'Создано по-другому',
    'about.p1': 'THK Enterprises основал Тимоти — 11-летний предприниматель из Мехико, который увидел пробел на рынке: организациям нужна профессиональная видеоинфраструктура, но они не могут позволить штатного AV-специалиста.',
    'about.p2': 'Мы используем кодеры Epiphan Pearl корпоративного класса, облачное управление и собственный AI-мониторинг для предоставления видео вещательного качества за малую часть традиционной стоимости.',
    'about.p3': 'Наш AI-ассистент (на базе Claude) работает 24/7 — доступен прямо сейчас для ответов на вопросы об интеграции, ценах или совместимости. Организации должны иметь возможность оценить платформу в любое время, а не только в рабочие часы.',

    // Contact
    'contact.tag': 'Связаться',
    'contact.title': 'Начать разговор',
    'contact.subtitle': 'Наш AI-ассистент доступен прямо сейчас. Форма ниже отправляется в реальный почтовый ящик — без автоответов, без обещаний времени ожидания.',
    'contact.info': 'Контактная информация',
    'contact.info.desc': 'Базируемся в Мехико. Работаем с организациями в Латинской и Северной Америке.',
    'contact.location': 'Адрес',
    'contact.email': 'Электронная почта',
    'contact.whatsapp': 'WhatsApp',
    'contact.availability': 'AI-ассистент',
    'contact.availability.value': 'Доступен 24/7 — поговорите сейчас',
    'contact.form.name': 'Полное имя',
    'contact.form.email': 'Электронная почта',
    'contact.form.phone': 'Телефон / WhatsApp',
    'contact.form.service': 'Что вам нужно?',
    'contact.form.service.select': 'Выберите услугу',
    'contact.form.service.viaas': 'VIaaS - Управляемый кодер',
    'contact.form.service.lecture': 'Постоянная запись лекций',
    'contact.form.service.livestream': 'Многокамерная трансляция',
    'contact.form.service.video': '4K видеопродакшн',
    'contact.form.message': 'Расскажите о ваших потребностях',
    'contact.form.message.placeholder': 'Сколько аудиторий/площадок? Что вы записываете?',
    'contact.form.submit': 'Отправить сообщение',
    'contact.form.disclaimer': 'Без спама. Без давления. Ваша информация конфиденциальна.',
    'contact.form.note': 'Предпочитаете писать? Используйте форму. Хотите поговорить сейчас? Чат ниже работает в реальном времени.',

    // Footer
    'footer.rights': 'THK Enterprises. Мехико. Все права защищены.',
    'footer.epiphan': 'При поддержке Epiphan Video',

    // Chat
    'chat.placeholder': 'Спросите о наших видеоуслугах...',
    'chat.powered': 'На базе Claude AI',
    'chat.cta.label': 'Спрашивайте — мы онлайн',

    // Form states
    'contact.form.success': 'Сообщение отправлено. Мы его получили.',
    'contact.form.error': 'Что-то пошло не так. Попробуйте чат.',
    'contact.form.sending': 'Отправка...',

    // Hero sub-label
    'hero.cta.chat.sub': 'Без форм. Мгновенные ответы.',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('en')

  const t = (key: string): string => {
    return translations[lang][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
